#!/bin/sh
#

# setup

if ! type wg >/dev/null; then
    apk add wireguard-tools-wg
    mkdir -p /etc/wireguard
fi

# config

cat <<EOF >/etc/wireguard/wg0.conf
{CONF}
EOF

cat <<EOF >/etc/wireguard/wg0.start
{START}
EOF

chmod +x /etc/wireguard/wg0.start

# startup

if [ ! -x /etc/init.d/local ]; then
    rc-update add local boot
fi

ln -sf /etc/wireguard/wg0.start /etc/local.d/

/etc/local.d/wg0.start
