#!/bin/sh
#

# setup

if ! type wg >/dev/null 2> &1; then
    apk add wireguard-tools-wg
    mkdir -p /etc/wireguard
fi

# config

cat <<EOF >/etc/wireguard/wg0.conf
{{CONF}}
EOF

cat <<EOF >/etc/wireguard/wg0.start
#!/bin/sh
#

sysctl -w net.ipv4.ip_forward=1

if type iptables >/dev/null 2>&1; then
  iptables -A FORWARD -i wg0 -j ACCEPT
  iptables -A FORWARD -o wg0 -j ACCEPT
  iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
fi

ip link add dev wg0 type wireguard
ip address add dev wg0 {{VIP}}
wg setconf wg0 /etc/wireguard/wg0.conf
ip link set up dev wg0
EOF

chmod +x /etc/wireguard/wg0.start

# auto start

if [ ! -x /etc/runlevels/boot/local ]; then
    rc-update add local boot
fi

ln -sf /etc/wireguard/wg0.start /etc/local.d/

# startup

/etc/local.d/wg0.start
