#!/bin/sh
#

# setup

if ! type wg >/dev/null; then
    yum install yum-plugin-elrepo
    yum install epel-release elrepo-release
    yum install kmod-wireguard wireguard-tools
    mkdir -p /etc/wireguard
fi

# config

cat <<EOF >/etc/wireguard/wg0.conf
{{CONF}}
EOF
