#!/bin/sh
#

# setup

if ! type wg >/dev/null; then
    yum install -y yum-plugin-elrepo
    yum install -y epel-release elrepo-release
    yum install -y kmod-wireguard wireguard-tools
    mkdir -p /etc/wireguard
fi

# config

cat <<EOF >/etc/wireguard/wg0.conf
{{CONF}}
EOF

cat <<EOF >/etc/wireguard/wg0.start
#!/bin/sh
#

sysctl -w net.ipv4.ip_forward=1

if type iptables >/dev/null; then
  iptables -A FORWARD -i wg0 -j ACCEPT
  iptables -A FORWARD -o wg0 -j ACCEPT
  iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
fi

ip link add dev wg0 type wireguard
ip address add dev wg0 {{VIP}}
wg setconf wg0 /etc/wireguard/wg0.conf
ip link set up dev wg0
EOF

chmod +x /etc/wireguard/wg0.start

# startup

cat <<EOF >>/etc/rc.d/rc.local
/etc/wireguard/wg0.start
EOF

/etc/wireguard/wg0.start
