#!/bin/sh
#

# setup

if ! type wg >/dev/null 2>&1; then
    apt install -y wireguard
    mkdir -p /etc/wireguard
fi

# config

cat <<EOF >/etc/wireguard/wg0.conf
{{CONF}}
EOF

cat <<EOF >/etc/wireguard/wg0.start
#!/bin/sh
#

sysctl -w net.ipv4.ip_forward=1

if type iptables >/dev/null 2>&1; then
  iptables -A FORWARD -i wg0 -j ACCEPT
  iptables -A FORWARD -o wg0 -j ACCEPT
  iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
fi

ip link add dev wg0 type wireguard
ip address add dev wg0 {{VIP}}
wg setconf wg0 /etc/wireguard/wg0.conf
ip link set up dev wg0
EOF

chmod +x /etc/wireguard/wg0.start

# service

cat <<EOF >>/etc/systemd/system/wg0.service
[Unit]
Description=wireguard interface 0
After=network.target

[Service]
Type=forking
ExecStart=/etc/wireguard/wg0.start
ExecReload=wg setconf wg0 /etc/wireguard/wg0.conf

[Install]
WantedBy=multi-user.target
EOF

chmod +x /etc/systemd/system/wg0.service

systemctl enable /etc/systemd/system/wg0.service
systemctl daemon-reload
systemctl start wg0
