kind: pipeline
name: default

steps:
  - name: build
    image: alpine
    commands:
      - sh docker/build
      - cp -av docker/* ./
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rehiy/wireguard-auto
      tags:
        - latest
