#!/bin/sh
#

# 支持自启

if [ ! -x /etc/init.d/local ]; then
    rc-update add local boot
fi

# 安装工具

if ! type wg >/dev/null; then
    apk add wireguard-tools-wg
    mkdir -p /etc/wireguard
fi

# 部署服务

export SERVER_IP=`wget -qO- http://v4.myip.la`

cp -av deploy/$SERVER_IP/* /etc/wireguard/

ln -sf /etc/wireguard/wg0.start /etc/local.d/
chmod +x /etc/wireguard/wg0.start

/etc/local.d/wg0.start
